# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 6) do

  create_table "auth_emails", :force => true do |t|
    t.column "mail_address", :string,   :limit => 256, :default => "",    :null => false
    t.column "bk_code",      :string,   :limit => 32
    t.column "invite_code",  :string,   :limit => 32,  :default => "",    :null => false
    t.column "auth_flag",    :boolean,                                    :null => false
    t.column "created_at",   :datetime
    t.column "stop_flag",    :boolean,                 :default => false
  end

  create_table "events", :force => true do |t|
    t.column "auth_email_id",  :integer,                                    :null => false
    t.column "html",           :string,   :limit => 128, :default => "",    :null => false
    t.column "public_flag",    :boolean,                                    :null => false
    t.column "post_at",        :datetime,                                   :null => false
    t.column "delivery_at",    :datetime
    t.column "delivered_flag", :boolean,                 :default => false
  end

  create_table "mobiles", :force => true do |t|
    t.column "ident",         :string,   :limit => 128, :default => "", :null => false
    t.column "auth_email_id", :integer,                                 :null => false
    t.column "nickname",      :string,   :limit => 32,  :default => "", :null => false
    t.column "remind_day",    :integer
    t.column "remind_time",   :string,                  :default => "", :null => false
    t.column "create_at",     :datetime
  end

end
